### ISSUE TITLE
"npm install pprof" not working

### ISSUE THREAD

**Issue by elgehelge** [google/pprof#523]
`npm install pprof` not working MacOS.

Hmm. This URL (see complete output further down) contains `unknown` which might not be desired?: `https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v2.0.0/node-v64-darwin-x64-unknown.tar.gz`

### What version of pprof are you using?
2.0.0

### What operating system and processor architecture are you using?
MacOS Catalina 10.15.3

As far as I know, Xcode is installed.
`xcode-select -p 1>/dev/null;echo $?` returns `0`

### What did you do?

Run `npm install pprof`

### What did you expect to see?
No errors

### What did you see instead?
```
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > protobufjs@6.8.9 postinstall /Users/my/project/folder/node_modules/pprof/node_modules/protobufjs
npm ERR! prepareGitDep > node scripts/postinstall
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > pprof@2.0.0 install /Users/my/project/folder/node_modules/pprof
npm ERR! prepareGitDep > node-pre-gyp install --fallback-to-build
npm ERR! prepareGitDep
npm ERR! prepareGitDep Failed to execute '/usr/local/Cellar/node@10/10.19.0/bin/node /usr/local/Cellar/node@10/10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown/pprof.node --module_name=pprof --module_path=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! prepareGitDep node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v2.0.0/node-v64-darwin-x64-unknown.tar.gz
npm ERR! prepareGitDep node-pre-gyp WARN Pre-built binaries not found for pprof@2.0.0 and node@10.19.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! prepareGitDep No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! prepareGitDep No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! prepareGitDep No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep gyp: No Xcode or CLT version detected!
npm ERR! prepareGitDep gyp ERR! configure error
npm ERR! prepareGitDep gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! prepareGitDep gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node@10/10.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! prepareGitDep gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
npm ERR! prepareGitDep gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm ERR! prepareGitDep gyp ERR! System Darwin 19.3.0
npm ERR! prepareGitDep gyp ERR! command "/usr/local/Cellar/node@10/10.19.0/bin/node" "/usr/local/Cellar/node@10/10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown/pprof.node" "--module_name=pprof" "--module_path=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
npm ERR! prepareGitDep gyp ERR! cwd /Users/my/project/folder/node_modules/pprof
npm ERR! prepareGitDep gyp ERR! node -v v10.19.0
npm ERR! prepareGitDep gyp ERR! node-gyp -v v5.0.5
npm ERR! prepareGitDep gyp ERR! not ok
npm ERR! prepareGitDep node-pre-gyp ERR! build error
npm ERR! prepareGitDep node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node@10/10.19.0/bin/node /usr/local/Cellar/node@10/10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown/pprof.node --module_name=pprof --module_path=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! prepareGitDep node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/my/project/folder/node_modules/pprof/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! prepareGitDep node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
npm ERR! prepareGitDep node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
npm ERR! prepareGitDep node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm ERR! prepareGitDep node-pre-gyp ERR! System Darwin 19.3.0
npm ERR! prepareGitDep node-pre-gyp ERR! command "/usr/local/Cellar/node@10/10.19.0/bin/node" "/Users/my/project/folder/node_modules/pprof/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! prepareGitDep node-pre-gyp ERR! cwd /Users/my/project/folder/node_modules/pprof
npm ERR! prepareGitDep node-pre-gyp ERR! node -v v10.19.0
npm ERR! prepareGitDep node-pre-gyp ERR! node-pre-gyp -v v0.14.0
npm ERR! prepareGitDep node-pre-gyp ERR! not ok
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! pprof@2.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the pprof@2.0.0 install script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/my/.npm/_logs/2020-04-20T09_33_17_505Z-debug.log
npm ERR! prepareGitDep
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > pprof@2.0.0 install /Users/my/project/folder/node_modules/pprof
npm ERR! prepareGitDep > node-pre-gyp install --fallback-to-build
npm ERR! prepareGitDep
npm ERR! prepareGitDep Failed to execute '/usr/local/Cellar/node@10/10.19.0/bin/node /usr/local/Cellar/node@10/10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown/pprof.node --module_name=pprof --module_path=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! prepareGitDep node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v2.0.0/node-v64-darwin-x64-unknown.tar.gz
npm ERR! prepareGitDep node-pre-gyp WARN Pre-built binaries not found for pprof@2.0.0 and node@10.19.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! prepareGitDep No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! prepareGitDep No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! prepareGitDep No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep gyp: No Xcode or CLT version detected!
npm ERR! prepareGitDep gyp ERR! configure error
npm ERR! prepareGitDep gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! prepareGitDep gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node@10/10.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! prepareGitDep gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
npm ERR! prepareGitDep gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm ERR! prepareGitDep gyp ERR! System Darwin 19.3.0
npm ERR! prepareGitDep gyp ERR! command "/usr/local/Cellar/node@10/10.19.0/bin/node" "/usr/local/Cellar/node@10/10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown/pprof.node" "--module_name=pprof" "--module_path=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
npm ERR! prepareGitDep gyp ERR! cwd /Users/my/project/folder/node_modules/pprof
npm ERR! prepareGitDep gyp ERR! node -v v10.19.0
npm ERR! prepareGitDep gyp ERR! node-gyp -v v5.0.5
npm ERR! prepareGitDep gyp ERR! not ok
npm ERR! prepareGitDep node-pre-gyp ERR! build error
npm ERR! prepareGitDep node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node@10/10.19.0/bin/node /usr/local/Cellar/node@10/10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown/pprof.node --module_name=pprof --module_path=/Users/my/project/folder/node_modules/pprof/build/node-v64-darwin-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! prepareGitDep node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/my/project/folder/node_modules/pprof/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! prepareGitDep node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
npm ERR! prepareGitDep node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
npm ERR! prepareGitDep node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm ERR! prepareGitDep node-pre-gyp ERR! System Darwin 19.3.0
npm ERR! prepareGitDep node-pre-gyp ERR! command "/usr/local/Cellar/node@10/10.19.0/bin/node" "/Users/my/project/folder/node_modules/pprof/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! prepareGitDep node-pre-gyp ERR! cwd /Users/my/project/folder/node_modules/pprof
npm ERR! prepareGitDep node-pre-gyp ERR! node -v v10.19.0
npm ERR! prepareGitDep node-pre-gyp ERR! node-pre-gyp -v v0.14.0
npm ERR! prepareGitDep node-pre-gyp ERR! not ok
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! pprof@2.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the pprof@2.0.0 install script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/my/.npm/_logs/2020-04-20T09_33_25_291Z-debug.log
npm ERR! prepareGitDep
npm ERR! code 1
npm ERR! null: npm exited with code 1 while attempting to build undefined. Clone the repository manually and run 'npm install' in it for more information.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/my/.npm/_logs/2020-04-20T09_33_25_737Z-debug.log
```

**Comment by kalyanac** [comment]
Please file this at https://github.com/google/pprof-nodejs.
